# This rule is not used by the project forma itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to account.form3.tech resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forma
    app.kubernetes.io/managed-by: kustomize
  name: account-viewer-role
rules:
- apiGroups:
  - account.form3.tech
  resources:
  - accounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - account.form3.tech
  resources:
  - accounts/status
  verbs:
  - get
