# This rule is not used by the project forma itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over account.form3.tech.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forma
    app.kubernetes.io/managed-by: kustomize
  name: account-admin-role
rules:
- apiGroups:
  - account.form3.tech
  resources:
  - accounts
  verbs:
  - '*'
- apiGroups:
  - account.form3.tech
  resources:
  - accounts/status
  verbs:
  - get
